# Generated by Django 5.2.6 on 2025-09-29 03:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création automatique', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification automatique', verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique généré automatiquement', primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('is_deleted', models.BooleanField(default=False, help_text="Marque l'enregistrement comme supprimé sans le supprimer physiquement", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date et heure de suppression logique', null=True, verbose_name='Date de suppression')),
                ('sync_status', models.CharField(choices=[('synced', 'Synchronisé'), ('pending', 'En attente de synchronisation'), ('conflict', 'Conflit de synchronisation'), ('error', 'Erreur de synchronisation')], default='pending', help_text='État de synchronisation avec la base distante', max_length=20, verbose_name='Statut de synchronisation')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Date et heure de dernière synchronisation réussie', null=True, verbose_name='Dernière synchronisation')),
                ('sync_hash', models.CharField(blank=True, help_text='Hash MD5 des données pour détecter les modifications', max_length=64, verbose_name='Hash de synchronisation')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage", verbose_name='Ordre')),
                ('image', models.ImageField(upload_to='articles/images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text="Description de l'image pour l'accessibilité", max_length=200, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Image d'article",
                'verbose_name_plural': "Images d'articles",
                'db_table': 'inventory_article_image',
                'ordering': ['article', 'order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création automatique', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification automatique', verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique généré automatiquement', primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('is_deleted', models.BooleanField(default=False, help_text="Marque l'enregistrement comme supprimé sans le supprimer physiquement", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date et heure de suppression logique', null=True, verbose_name='Date de suppression')),
                ('sync_status', models.CharField(choices=[('synced', 'Synchronisé'), ('pending', 'En attente de synchronisation'), ('conflict', 'Conflit de synchronisation'), ('error', 'Erreur de synchronisation')], default='pending', help_text='État de synchronisation avec la base distante', max_length=20, verbose_name='Statut de synchronisation')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Date et heure de dernière synchronisation réussie', null=True, verbose_name='Dernière synchronisation')),
                ('sync_hash', models.CharField(blank=True, help_text='Hash MD5 des données pour détecter les modifications', max_length=64, verbose_name='Hash de synchronisation')),
                ('old_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Ancien prix d'achat")),
                ('old_selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ancien prix de vente')),
                ('new_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Nouveau prix d'achat")),
                ('new_selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nouveau prix de vente')),
                ('reason', models.CharField(choices=[('cost_increase', 'Augmentation coût fournisseur'), ('cost_decrease', 'Diminution coût fournisseur'), ('margin_adjustment', 'Ajustement marge'), ('promotion', 'Promotion'), ('market_adjustment', 'Ajustement marché'), ('currency_change', 'Variation devise'), ('bulk_update', 'Mise à jour en masse'), ('manual', 'Modification manuelle')], max_length=20, verbose_name='Raison du changement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'effet")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.article', verbose_name='Article')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cet enregistrement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a modifié cet enregistrement en dernier', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Historique de prix',
                'verbose_name_plural': 'Historiques de prix',
                'db_table': 'inventory_price_history',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création automatique', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification automatique', verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID unique généré automatiquement', primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('is_deleted', models.BooleanField(default=False, help_text="Marque l'enregistrement comme supprimé sans le supprimer physiquement", verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date et heure de suppression logique', null=True, verbose_name='Date de suppression')),
                ('sync_status', models.CharField(choices=[('synced', 'Synchronisé'), ('pending', 'En attente de synchronisation'), ('conflict', 'Conflit de synchronisation'), ('error', 'Erreur de synchronisation')], default='pending', help_text='État de synchronisation avec la base distante', max_length=20, verbose_name='Statut de synchronisation')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Date et heure de dernière synchronisation réussie', null=True, verbose_name='Dernière synchronisation')),
                ('sync_hash', models.CharField(blank=True, help_text='Hash MD5 des données pour détecter les modifications', max_length=64, verbose_name='Hash de synchronisation')),
                ('conversion_factor', models.DecimalField(decimal_places=6, help_text="Multiplicateur pour convertir de l'unité source vers l'unité cible", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Facteur de conversion')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='inventory.unitofmeasure', verbose_name='Unité source')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='inventory.unitofmeasure', verbose_name='Unité cible')),
            ],
            options={
                'verbose_name': "Conversion d'unité",
                'verbose_name_plural': "Conversions d'unités",
                'db_table': 'inventory_unit_conversion',
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
